# Generated by Django 4.2 on 2023-05-17 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='hora',
            field=models.TimeField(default=datetime.time(19, 43, 45, 67119)),
        ),
    ]
