# Generated by Django 4.2 on 2023-06-11 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_users_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(default='DEFAULT_VALUE', max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(default=datetime.time(17, 7, 36, 266711))),
                ('mensaje', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
